name: shared_preferences_dtx
description: A package that simplifies the access most of used properties/functions right in the package shared_preferences.
version: 1.1.4
repository: https://github.com/Zambiee/dtx/tree/main/packages/other_packages/shared_preferences_dtx
issue_tracker: https://github.com/zambiee/dtx/issues
homepage: https://github.com/zambiee/dtx
documentation: https://github.com/zambiee/dtx

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
