name: Flutter Context DTX

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/flutter/flutter_context_dtx/**"
      - ".github/workflows/flutter_context_dtx.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/flutter/flutter_context_dtx/**"
      - ".github/workflows/flutter_context_dtx.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/other_packages/shared_preferences_dtx
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter packages get
      - name: Check format
        run: flutter format --set-exit-if-changed lib example
      - name: Analyze
        run: flutter analyze lib example