name: Flutter Context DTX

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/flutter/flutter_context_dtx/**"
      - ".github/workflows/flutter_context_dtx.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/flutter/flutter_context_dtx/**"
      - ".github/workflows/flutter_context_dtx.yaml"

jobs:
  build:
    uses: kmartins/workflows/.github/workflows/flutter_package.yaml@flutter_package-v1.0.2
    with:
      working_directory: packages/flutter/flutter_context_dtx
      flutter_version: 3.13.2
      format_directories: lib example
      analyze_directories: lib example
      run_tests: false
      check_coverage: false
      upload_coverage_codecov: false

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: packages/flutter/flutter_context_dtx
