name: Flutter Context DTX

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/flutter/flutter_context_dtx/**"
      - ".github/workflows/flutter_context_dtx.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/flutter/flutter_context_dtx/**"
      - ".github/workflows/flutter_context_dtx.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/flutter/flutter_context_dtx
      format_directories: lib
      analyze_directories: lib

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: packages/flutter/flutter_context_dtx
