name: Publish Flutter Context DTX in the pub.dev

on:
  push:
    tags:
      - "flutter_context_dtx-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    permissions:
      id-token: write
    uses: kmartins/workflows/.github/workflows/publish_flutter_package.yaml@v1.0.0
    with:
      working_directory: packages/flutter/flutter_context_dtx
      environment: flutter_context_dtx
      pub_credentials: secrets.PUB_CREDENTIALS
